In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [2]:
data = pd.read_csv('Part 8 - Deep Learning\Section 39 - Artificial Neural Networks (ANN)\Python\Churn_Modelling.csv')

In [3]:
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [8]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [10]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [13]:
ann = tf.keras.models.Sequential()

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation = 'relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation = 'relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1,activation = 'sigmoid'))

In [17]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [18]:
ann.fit(x_train,y_train,batch_size = 32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 774us/step - loss: 0.5679 - accuracy: 0.7674
Epoch 2/100
250/250 [==============================] - 0s 764us/step - loss: 0.4908 - accuracy: 0.8011
Epoch 3/100
250/250 [==============================] - 0s 762us/step - loss: 0.4491 - accuracy: 0.8174
Epoch 4/100
250/250 [==============================] - 0s 754us/step - loss: 0.4253 - accuracy: 0.8254
Epoch 5/100
250/250 [==============================] - 0s 766us/step - loss: 0.4138 - accuracy: 0.8280
Epoch 6/100
250/250 [==============================] - 0s 762us/step - loss: 0.4072 - accuracy: 0.8291
Epoch 7/100
250/250 [==============================] - 0s 842us/step - loss: 0.4026 - accuracy: 0.8304
Epoch 8/100
250/250 [==============================] - 0s 783us/step - loss: 0.3989 - accuracy: 0.8310
Epoch 9/100
250/250 [==============================] - 0s 826us/step - loss: 0.3953 - accuracy: 0.8298
Epoch 10/100
250/250 [==============================] - 0s 768us/step - l

In [20]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,5000]]))>0.5)

1/1 [==============================] - 0s 20ms/step
[[False]]


In [21]:
import pickle

In [22]:
pickle.dump(ann,open('annmodel.pkl','wb'))

In [23]:
pickled_model = pickle.load(open('annmodel.pkl','rb'))

In [27]:
pickled_model.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,5000]]))>0.5

1/1 [==============================] - 0s 50ms/step


array([[False]])